apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dl-sentinel2-contry-
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: regions
        value: '[{"country": "BE100", "startDate": "2018-05-01", "endDate": "2018-09-01", "sampleProp": 0.05, "exportCLC": true},
                 {"country": "BE251", "startDate": "2018-05-01", "endDate": "2018-09-01", "sampleProp": 0.05, "exportCLC": true},
                 {"country": "FRK26", "startDate": "2018-05-01", "endDate": "2018-09-01", "sampleProp": 0.05, "exportCLC": true},
                 {"country": "FRJ27", "startDate": "2018-05-01", "endDate": "2018-09-01", "sampleProp": 0.05, "exportCLC": true},
                 {"country": "BE100", "startDate": "2021-05-01", "endDate": "2021-09-01", "sampleProp": 0.05, "exportCLC": true},
                 {"country": "BE251", "startDate": "2021-05-01", "endDate": "2021-09-01", "sampleProp": 0.05, "exportCLC": true},
                 {"country": "FRK26", "startDate": "2021-05-01", "endDate": "2021-09-01", "sampleProp": 0.05, "exportCLC": true},
                 {"country": "FRJ27", "startDate": "2021-05-01", "endDate": "2021-09-01", "sampleProp": 0.05, "exportCLC": true}]'
  templates:
    # Entrypoint DAG template
    - name: main
      dag:
        tasks:
          - name: run-dl
            template: run-dl-task
            arguments:
              parameters:
                - name: country
                  value: "{{item.country}}"
                - name: startDate
                  value: "{{item.startDate}}"
                - name: endDate
                  value: "{{item.endDate}}"
                - name: sampleProp
                  value: "{{item.sampleProp}}"
                - name: exportCLC
                  value: "{{item.exportCLC}}"
            withParam: "{{workflow.parameters.regions}}"

    # Worker template
    - name: run-dl-task
      inputs:
        parameters:
          - name: country
          - name: startDate
          - name: endDate
          - name: sampleProp
          - name: exportCLC
      container:
        image: rayaberova/hackathon-ntts-2025:main
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: [
           "git clone https://github.com/InseeFrLab/hackathon-ntts-2025.git &&
           cd hackathon-ntts-2025/preprocess &&
           export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
           mc cp s3/projet-hackathon-ntts-2025/country_RG_01M_2021_4326_LEVL_3.gpkg data/ &&
           source ./setup_argo.sh &&
           python main_country.py --country {{inputs.parameters.country}} --startDate {{inputs.parameters.startDate}} --endDate {{inputs.parameters.endDate}} --sampleProp {{inputs.parameters.sampleProp}} --exportCLC {{inputs.parameters.exportCLC}}"
        ]
        env:
          - name: PROJ_LIB
            value: /opt/conda/share/proj
          - name: GCP_AUTH_PROVIDER
            value: https://www.googleapis.com/oauth2/v1/certs
          - name: GCP_AUTH_URI
            value: https://accounts.google.com/o/oauth2/auth
          - name: GCP_CLIENT_CERT
            value: https://www.googleapis.com/robot/v1/metadata/x509/slums-detection-sa%40ee-insee-sentinel.iam.gserviceaccount.com
          - name: GCP_CLIENT_EMAIL
            value: slums-detection-sa@ee-insee-sentinel.iam.gserviceaccount.com
          - name: GCP_PROJECT_ID
            value: ee-insee-sentinel
          - name: GCP_TOKEN_URI
            value: https://oauth2.googleapis.com/token
          - name: GCP_TYPE
            value: service_account
          - name: GCP_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: gcp
                key: gcpPrivateKey
          - name: GCP_PRIVATE_KEY_ID
            valueFrom:
              secretKeyRef:
                name: gcp
                key: gcpPrivateKeyId
          - name: GCP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: gcp
                key: gcpClientId
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: mc-s3
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: mc-s3
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
